import type { Employee, PromotionStats, PromotionRecord, RankingItem, OfficialAccount } from '../types';

// 模拟公众号列表
export const mockOfficialAccounts: OfficialAccount[] = [
  { id: 'OA001', name: '科技前沿', avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=tech' },
  { id: 'OA002', name: '生活百科', avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=life' },
  { id: 'OA003', name: '美食探店', avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=food' },
];

// 模拟当前登录员工
export const mockCurrentEmployee: Employee = {
  id: 'EMP001',
  employeeId: 'EMP001',
  name: '张三',
  department: '销售部',
  phone: '13800138000',
  qrCodeUrl: '',
  wechatOpenId: '',
  isBound: true,
  createdAt: '2024-01-15 10:00:00',
};

// 模拟推广统计
export const mockPromotionStats: PromotionStats = {
  employeeId: 'EMP001',
  employeeName: '张三',
  scanCount: 156,
  followCount: 118,
  todayScanCount: 5,
  todayFollowCount: 3,
  monthScanCount: 45,
  monthFollowCount: 32,
};

// 模拟推广记录（包含公众号信息）
export const mockPromotionRecords: PromotionRecord[] = [
  // 今日记录（2026-03-20）
  {
    id: '1',
    employeeId: 'EMP001',
    employeeName: '张三',
    accountId: 'OA001',
    accountName: '科技前沿',
    accountAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=tech',
    scanTime: '2026-03-20 15:30:25',
    isFollowed: true,
    followTime: '2026-03-20 15:30:58',
    nickname: '用户A',
  },
  {
    id: '2',
    employeeId: 'EMP001',
    employeeName: '张三',
    accountId: 'OA002',
    accountName: '生活百科',
    accountAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=life',
    scanTime: '2026-03-20 14:20:15',
    isFollowed: true,
    followTime: '2026-03-20 14:20:42',
    nickname: '用户B',
  },
  {
    id: '3',
    employeeId: 'EMP001',
    employeeName: '张三',
    accountId: 'OA001',
    accountName: '科技前沿',
    accountAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=tech',
    scanTime: '2026-03-20 13:10:08',
    isFollowed: false,
  },
  {
    id: '4',
    employeeId: 'EMP001',
    employeeName: '张三',
    accountId: 'OA003',
    accountName: '美食探店',
    accountAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=food',
    scanTime: '2026-03-20 10:45:30',
    isFollowed: true,
    followTime: '2026-03-20 10:46:15',
    nickname: '用户C',
  },
  {
    id: '5',
    employeeId: 'EMP001',
    employeeName: '张三',
    accountId: 'OA002',
    accountName: '生活百科',
    accountAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=life',
    scanTime: '2026-03-20 09:30:00',
    isFollowed: false,
  },
  // 本周记录（2026-03-14 至 2026-03-19）
  {
    id: '6',
    employeeId: 'EMP001',
    employeeName: '张三',
    accountId: 'OA001',
    accountName: '科技前沿',
    accountAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=tech',
    scanTime: '2026-03-19 16:20:45',
    isFollowed: true,
    followTime: '2026-03-19 16:21:30',
    nickname: '用户D',
  },
  {
    id: '7',
    employeeId: 'EMP001',
    employeeName: '张三',
    accountId: 'OA003',
    accountName: '美食探店',
    accountAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=food',
    scanTime: '2026-03-19 14:15:30',
    isFollowed: false,
  },
  {
    id: '8',
    employeeId: 'EMP001',
    employeeName: '张三',
    accountId: 'OA002',
    accountName: '生活百科',
    accountAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=life',
    scanTime: '2026-03-18 11:45:30',
    isFollowed: true,
    followTime: '2026-03-18 11:46:15',
    nickname: '用户E',
  },
  {
    id: '9',
    employeeId: 'EMP001',
    employeeName: '张三',
    accountId: 'OA001',
    accountName: '科技前沿',
    accountAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=tech',
    scanTime: '2026-03-17 10:30:22',
    isFollowed: true,
    followTime: '2026-03-17 10:31:05',
    nickname: '用户F',
  },
  {
    id: '10',
    employeeId: 'EMP001',
    employeeName: '张三',
    accountId: 'OA003',
    accountName: '美食探店',
    accountAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=food',
    scanTime: '2026-03-16 18:20:45',
    isFollowed: false,
  },
  {
    id: '11',
    employeeId: 'EMP001',
    employeeName: '张三',
    accountId: 'OA002',
    accountName: '生活百科',
    accountAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=life',
    scanTime: '2026-03-15 16:15:30',
    isFollowed: true,
    followTime: '2026-03-15 16:16:22',
    nickname: '用户G',
  },
  {
    id: '12',
    employeeId: 'EMP001',
    employeeName: '张三',
    accountId: 'OA001',
    accountName: '科技前沿',
    accountAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=tech',
    scanTime: '2026-03-14 14:50:18',
    isFollowed: true,
    followTime: '2026-03-14 14:51:05',
    nickname: '用户H',
  },
  // 本月记录（2026-02-20 至 2026-03-13）
  {
    id: '13',
    employeeId: 'EMP001',
    employeeName: '张三',
    accountId: 'OA003',
    accountName: '美食探店',
    accountAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=food',
    scanTime: '2026-03-10 14:50:18',
    isFollowed: true,
    followTime: '2026-03-10 14:51:05',
    nickname: '用户I',
  },
  {
    id: '14',
    employeeId: 'EMP001',
    employeeName: '张三',
    accountId: 'OA002',
    accountName: '生活百科',
    accountAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=life',
    scanTime: '2026-03-05 09:30:00',
    isFollowed: true,
    followTime: '2026-03-05 09:30:45',
    nickname: '用户J',
  },
  {
    id: '15',
    employeeId: 'EMP001',
    employeeName: '张三',
    accountId: 'OA001',
    accountName: '科技前沿',
    accountAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=tech',
    scanTime: '2026-02-28 11:00:00',
    isFollowed: false,
  },
  {
    id: '16',
    employeeId: 'EMP001',
    employeeName: '张三',
    accountId: 'OA003',
    accountName: '美食探店',
    accountAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=food',
    scanTime: '2026-02-25 15:20:30',
    isFollowed: true,
    followTime: '2026-02-25 15:21:10',
    nickname: '用户K',
  },
  {
    id: '17',
    employeeId: 'EMP001',
    employeeName: '张三',
    accountId: 'OA002',
    accountName: '生活百科',
    accountAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=life',
    scanTime: '2026-02-22 10:00:00',
    isFollowed: false,
  },
  // 更早的记录（不在本月范围内）
  {
    id: '18',
    employeeId: 'EMP001',
    employeeName: '张三',
    accountId: 'OA001',
    accountName: '科技前沿',
    accountAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=tech',
    scanTime: '2026-02-10 10:00:00',
    isFollowed: false,
  },
];

// 模拟今日排行榜
export const mockTodayRanking: RankingItem[] = [
  { rank: 1, employeeId: 'EMP002', employeeName: '李四', department: '市场部', scanCount: 12, followCount: 10 },
  { rank: 2, employeeId: 'EMP003', employeeName: '王五', department: '销售部', scanCount: 10, followCount: 8 },
  { rank: 3, employeeId: 'EMP001', employeeName: '张三', department: '销售部', scanCount: 5, followCount: 3, isMe: true },
  { rank: 4, employeeId: 'EMP004', employeeName: '赵六', department: '客服部', scanCount: 4, followCount: 3 },
  { rank: 5, employeeId: 'EMP005', employeeName: '钱七', department: '运营部', scanCount: 3, followCount: 2 },
];

// 模拟本月排行榜
export const mockMonthRanking: RankingItem[] = [
  { rank: 1, employeeId: 'EMP003', employeeName: '王五', department: '销售部', scanCount: 65, followCount: 52 },
  { rank: 2, employeeId: 'EMP002', employeeName: '李四', department: '市场部', scanCount: 58, followCount: 45 },
  { rank: 3, employeeId: 'EMP001', employeeName: '张三', department: '销售部', scanCount: 45, followCount: 36, isMe: true },
  { rank: 4, employeeId: 'EMP004', employeeName: '赵六', department: '客服部', scanCount: 38, followCount: 30 },
  { rank: 5, employeeId: 'EMP005', employeeName: '钱七', department: '运营部', scanCount: 32, followCount: 25 },
];

// 模拟所有员工（用于绑定验证）
export const mockAllEmployees: Employee[] = [
  {
    id: 'EMP001',
    employeeId: 'EMP001',
    name: '张三',
    department: '销售部',
    phone: '13800138000',
    qrCodeUrl: '',
    wechatOpenId: '',
    isBound: true,
    createdAt: '2024-01-15 10:00:00',
  },
  {
    id: 'EMP002',
    employeeId: 'EMP002',
    name: '李四',
    department: '市场部',
    phone: '13800138001',
    qrCodeUrl: '',
    wechatOpenId: '',
    isBound: false,
    createdAt: '2024-02-20 10:00:00',
  },
  {
    id: 'EMP003',
    employeeId: 'EMP003',
    name: '王五',
    department: '销售部',
    phone: '13800138002',
    qrCodeUrl: '',
    wechatOpenId: '',
    isBound: false,
    createdAt: '2024-03-10 10:00:00',
  },
];